drop table  IF EXISTS  T_FLOW_PAY_APPROVAL ;
CREATE TABLE `T_FLOW_PAY_APPROVAL` (
  `ID` bigint(20) NOT NULL AUTO_INCREMENT,
  `APPLY_USER_ID` varchar(256) DEFAULT NULL COMMENT '发起人ID',
  `APPLY_USER_NAME` varchar(256) DEFAULT NULL COMMENT '发起人名称',
  
  `PROJECT_NAME` varchar(256) DEFAULT NULL COMMENT '项目名称',
  `CONTRACT_NUM` varchar(256) DEFAULT NULL COMMENT '合同编号',
  `PROGRESS_PAY_MONTH` varchar(256) DEFAULT NULL COMMENT '进度款月份',   
  `PAY_REMARK` varchar(1000) DEFAULT NULL COMMENT '付款说明',   
   
  `CREATEBY` bigint(20) NOT NULL COMMENT '创建者id',
  `CREATEBY_NAME` varchar(32) NOT NULL COMMENT '创建者名称',
  `CREATE_DATE` datetime NOT NULL COMMENT '创建时间',
  `UPDATEBY` bigint(20) DEFAULT NULL COMMENT '修改者id',
  `UPDATEBY_NAME` varchar(32) DEFAULT NULL COMMENT '修改者名称',
  `UPDATE_DATE` datetime DEFAULT NULL COMMENT '修改时间',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='付款审批业务表';